source1:
  type: csv
  path: testdata/testcase1_simple_csv/source1.csv

source2:
  type: csv  
  path: testdata/testcase1_simple_csv/source2.csv

output:
  final_report: time_based_final_report.yaml
  periodic_reports: time_based_periodic_reports

periodic:
  enabled: true
  time_interval_seconds: 3
  record_interval: 0